
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_Golden_Top(
	ADC_CLK_10,
	MAX10_CLK1_50,
	MAX10_CLK2_50,
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_N,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_N,
	DRAM_DQ,
	DRAM_LDQM,
	DRAM_RAS_N,
	DRAM_UDQM,
	DRAM_WE_N,
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,
	KEY,
	LEDR,
	SW,
	VGA_B,
	VGA_G,
	VGA_HS,
	VGA_R,
	VGA_VS,
	GSENSOR_CS_N,
	GSENSOR_INT,
	GSENSOR_SCLK,
	GSENSOR_SDI,
	GSENSOR_SDO,
	ARDUINO_IO,
	ARDUINO_RESET_N,
	GPIO
);

	//////////// CLOCK //////////
	input ADC_CLK_10;
	input MAX10_CLK1_50;
	input MAX10_CLK2_50;

	//////////// SDRAM //////////
	output [12:0] DRAM_ADDR;
	output [1:0] DRAM_BA;
	output DRAM_CAS_N;
	output DRAM_CKE;
	output DRAM_CLK;
	output DRAM_CS_N;
	inout [15:0] DRAM_DQ;
	output DRAM_LDQM;
	output DRAM_RAS_N;
	output DRAM_UDQM;
	output DRAM_WE_N;

	//////////// SEG7 //////////
	output [7:0] HEX0;
	output [7:0] HEX1;
	output [7:0] HEX2;
	output [7:0] HEX3;
	output [7:0] HEX4;
	output [7:0] HEX5;

	//////////// KEY //////////
	input [1:0] KEY;

	//////////// LED //////////
	output [9:0] LEDR;

	//////////// SW //////////
	input [9:0] SW;

	//////////// VGA //////////
	output [3:0] VGA_B;
	output [3:0] VGA_G;
	output VGA_HS;
	output [3:0] VGA_R;
	output VGA_VS;

	//////////// Accelerometer //////////
	output GSENSOR_CS_N;
	input [2:1] GSENSOR_INT;
	output GSENSOR_SCLK;
	inout GSENSOR_SDI;
	inout GSENSOR_SDO;

	//////////// Arduino //////////
	inout [15:0] ARDUINO_IO;
	inout ARDUINO_RESET_N;

	//////////// GPIO; GPIO connect to GPIO Default //////////
	inout [35:0] GPIO;



	//=======================================================
	//  REG/WIRE declarations
	//=======================================================




	//=======================================================
	//  Structural coding
	//=======================================================



endmodule
